# -*- coding: utf-8 -*-
"""Koustav_Day02_AI_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vPNe5HBHqcBlVww2CpfuM4a8DFmGAc6
"""

# String and its methods

text = "Hello World"
print(text.upper()) #HELLO WORLD
print(text.lower()) #hello world
print(text.title()) #Hello World
print(text.capitalize()) #Hello World
print(text.replace("world","Hello"))
print(text.find("world")) #6
print(len(text))   #11

#List and its methods

number = [10 , 20 , 30]
number.append(40)
print(number)
number.insert(1,15) #add to index 1
print(number) #remove value

number.remove(20) # remove value
print(number)

number.pop()     #remove last item
print(number)

number.sort()    #sort list
print(number)

number.reverse() #reverse the list
print(number)

for i in range(1,6):
  print(i)

num = 1
while num<10:
  print("Hello World")
  num += 1

for i in range(1,10):
  if i==5:
    break
    print(i)

name = "python"
print(name)
print(len(name)) #6
print(type(name)) # <class 'str'>

numbers = [10,20,30]
print(sum(numbers))
print(max(numbers))
print(min(numbers))

# User Defined Function
def greet():
  print("Welcome to print class")

greet()

#Sum of two Number using function
def add(a, b):
  return a + b
result = add(20,30)
print(f"The Value of sum of a & b is: {result}")

print("---------------------Welcome to Grade Calculator-------------------------------")

name = input("Enter a Student Name:")

sub1 = float(input("Enter yout marks for subject 1"))
sub2 = float(input("Enter yout marks for subject 2"))
sub3 = float(input("Enter yout marks for subject 3"))
sub4 = float(input("Enter yout marks for subject 4"))
sub5 = float(input("Enter yout marks for subject 5"))

total = sub1 + sub2 + sub3 +sub4 + sub5
avg = total/5

if avg >= 90:
    grade = "A+"
elif avg >= 80:
    grade = "A"
elif avg >= 70:
    grade = "B"
elif avg >= 60:
    grade = "C"
elif avg >= 50:
    grade = "D"
else:
    grade = "F"


print("\n --- Result ---")
print("Student Name:", name)
print("Total Marks:", total)
print("Average Marks:", avg)
print("Grade", grade)