# -*- coding: utf-8 -*-
"""Koustav_Day01_AI_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMmWhnj6hytPjVYApoF_D6D8xcG1cgN0
"""

# Build a Calculator Program
# Concept : Type Casting , Variable , Data Types,I/O function , Comments(Documentation)

a = int(input("Enter the 1st Number"))
b = int(input("Enter the 2nd Number"))
print(f"Addition is: {a+b}") #F string(Very Crucial)
print(f"Subtraction is:{a-b}")
print(f"Multiplication is:{a*b}")
print(f"Division is:{a/b}")

"""Project 2:Student Information"""

name = input("Enter your name")
age = int(input("Enter your Age"))
dept = input("Enter your Department:")

print(f"My Name is {name}, age {age}, and my Deparment is {dept}")

"""# Take city as a input"""

city = input("Enter your city name: ")
print(f"Your City is {city}")

# input 2 numbers and give thier sum

a = float(input("Enter 1st number or decimal "))
b = float(input("Enter 2nd number or decimal "))

print(a+b)

# Create variable for name, salary, job role

name = input("Enter your name:")
salary = float(input("Enter your salary"))
jobRole = input("Enter yout Job Role")

print(f"My name is :{name}, my is salary is {salary}, and my Role is {jobRole}")

# Print welcome messeage using input

message = input("Enter your Message: ")
print(message)

#Popular Data Types in Python

#List vs Tuple

roles = ["AI Engineer","Sodtware Developer","Tech Lead"] #list
ages = (2000,4000,6000) #tuple

# SET vs Dictionary
name ={"Alex", "Yuli"} # set
age = {"Alex", "Data Scientist","Yuli"} # dictionary

thisdict = {
  "brand": "Ford", # key : value
  "model": "Mustang"
} # dict

# if- else staements & indentation
# lets check you are eligable for driving

age = int(input("Enter your Age"))

if age >= 18 :
  print("You shall Drive")
if age < 18 :
  print("You should not Drive")

# if-else-elif statements & indentation
# logical operator and,or and not

a = int(input("Enter a"))
b = int(input("Enter b"))
c = int(input("Enter c"))

if a>b and a>c:
  print("a is the greatest: ")
elif b>a and b>c:
  print("b is the greatest: ")
else:
  print("c is the greatest: ")

# Modules = python file(numerous inbuilt functions)
import math

a = 25
print(math.sqrt(a))

# how to print todays date and time

import datetime

a = datetime.datetime.now()
print(a)

# in future when we make projects we use modules like this :


import numpy
import pandas as pd
import matplotlib
import tensorflow
import pygame